VivesActivities.Ui.Mvc/Models/ErrorViewModel.cs
namespace VivesActivities.Ui.Mvc.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

VivesActivities.Ui.Mvc/Models/VivesActivity.cs
namespace VivesActivities.Ui.Mvc.Models
{
    public class VivesActivity
    {
        public int Id { get; set; }
        public required string Name { get; set; }
        public string? Description { get; set; }
        public string? Type { get; set; }
        public required string Location { get; set; }
    }
}

VivesActivities.Ui.Mvc/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using VivesActivities.Ui.Mvc.Core;
using VivesActivities.Ui.Mvc.Models;
using Activity = System.Diagnostics.Activity;

namespace VivesActivities.Ui.Mvc.Controllers
{
    public class HomeController : Controller
    {
        private readonly Database _database;

        public HomeController(Database database)
        {
            _database = database;
        }

        public IActionResult Index()
        {
            var activities = _database.Activities;
            return View(activities);
        }

        public IActionResult About()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        
    }
}

VivesActivities.Ui.Mvc/Controllers/VivesActivitiesController.cs
using Microsoft.AspNetCore.Mvc;
using VivesActivities.Ui.Mvc.Core;
using VivesActivities.Ui.Mvc.Models;

namespace VivesActivities.Ui.Mvc.Controllers
{
    public class VivesActivitiesController : Controller
    {
        private readonly Database _database;
        public VivesActivitiesController(Database database)
        {
            _database = database;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var activities = _database.Activities;
            return View(activities);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(VivesActivity activity)
        {
            _database.Activities.Add(activity);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var activity = _database.Activities
                .FirstOrDefault(a => a.Id == id);

            if (activity is null)
            {
                return RedirectToAction("Index");
            }

            return View(activity);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(VivesActivity activity)
        {
            var dbActivity = _database.Activities
                .FirstOrDefault(a => a.Id == activity.Id);

            if (dbActivity is null)
            {
                return RedirectToAction("Index");
            }

            dbActivity.Name = activity.Name;
            dbActivity.Description = activity.Description;
            dbActivity.Type = activity.Type;
            dbActivity.Location = activity.Location;

            return RedirectToAction("Index");
        }
    }
}

VivesActivities.Ui.Mvc/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About page";
}
<h1>@ViewData["Title"]</h1>

<p>This is the about page.</p>
<img src="~/images/waterfall.jpg" width="500" alt="Waterfall"/>

VivesActivities.Ui.Mvc/Views/Home/Index.cshtml
@model IList<VivesActivity>
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

<h2>Featured</h2>
@{
    var firstActivity = Model.FirstOrDefault();
    if (firstActivity is not null)
    {
        <partial name="VivesActivityPartial" model="firstActivity"/>
    }
}
<h2>All activities</h2>
<div class="row">
@foreach (var activity in Model)
{
    <div class="col-4">
       <partial name="VivesActivityPartial" model="activity"/>
    </div>
}
</div>

VivesActivities.Ui.Mvc/Views/Home/VivesActivityPartial.cshtml
@model VivesActivity

<div class="card mb-2" style="width: 18rem;">
    <div class="card-body">
        <h5 class="card-title">@Model.Name</h5>
        <h6 class="card-subtitle mb-2 text-muted">@Model.Type at @Model.Location</h6>
        <p class="card-text">@Model.Description</p>
        @* <a href="#" class="card-link">Card link</a>
                <a href="#" class="card-link">Another link</a> *@
    </div>
</div>

VivesActivities.Ui.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VivesActivities.Ui.Mvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/VivesActivities.Ui.Mvc.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">VivesActivities.Ui.Mvc</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="VivesActivities" asp-action="Index">Activities</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - VivesActivities.Ui.Mvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

VivesActivities.Ui.Mvc/Views/VivesActivities/Create.cshtml
@model VivesActivity
@{
    ViewData["Title"] = "Create activity";
}

<h1>@ViewData["Title"]</h1>

<form method="post">
    <div class="mb-3">
        <label asp-for="Name" class="form-label"></label>
        <input asp-for="Name" class="form-control"/>
    </div>
    <div class="mb-3">
        <label asp-for="Location" class="form-label"></label>
        <input asp-for="Location" class="form-control" />
    </div>
    <div class="mb-3">
        <label asp-for="Type" class="form-label"></label>
        <input asp-for="Type" class="form-control" />
    </div>
    <div class="mb-3">
        <label asp-for="Description" class="form-label"></label>
        <textarea asp-for="Description" class="form-control"></textarea>
    </div>
    <button type="submit" class="btn btn-primary">Create</button>
</form>

VivesActivities.Ui.Mvc/Views/VivesActivities/Edit.cshtml
@model VivesActivity
@{
    ViewData["Title"] = $"Edit activity {Model.Name}";
}

<h1>@ViewData["Title"]</h1>

<form method="post">
    <div class="mb-3">
        <label asp-for="Name" class="form-label"></label>
        <input asp-for="Name" class="form-control"/>
    </div>
    <div class="mb-3">
        <label asp-for="Location" class="form-label"></label>
        <input asp-for="Location" class="form-control" />
    </div>
    <div class="mb-3">
        <label asp-for="Type" class="form-label"></label>
        <input asp-for="Type" class="form-control" />
    </div>
    <div class="mb-3">
        <label asp-for="Description" class="form-label"></label>
        <textarea asp-for="Description" class="form-control"></textarea>
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
</form>

VivesActivities.Ui.Mvc/Views/VivesActivities/Index.cshtml
@model IList<VivesActivity>
@{
    ViewData["Title"] = "Manage Activies";
}

<h1>@ViewData["Title"]</h1>

<a asp-action="Create" class="btn btn-primary">New Activity</a>

<table class="table table-dark table-striped">
    <thead>
    <tr>
        <th>Name</th>
        <th>Location</th>
        <th>Type</th>
        <th>Actions</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var activity in Model)
    {
        <partial name="VivesActivityRowPartial" model="activity"/>
    }
    </tbody>
</table>

VivesActivities.Ui.Mvc/Views/VivesActivities/VivesActivityRowPartial.cshtml
@model VivesActivity

<tr>
    <td>@Model.Name</td>
    <td>@Model.Location</td>
    <td>@Model.Type</td>
    <td>
        <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-secondary">Edit</a>
    </td>
</tr>